### ISSUE TITLE
Chunk preload and Force Chunk preload not working.

### ISSUE THREAD

**Issue by Nato390** [daipenger/minema#13]
First off, Apologies if this has been discussed before or if this is a simple mistake on my end.

I am trying to use this mod to render footage similar to Acid Interstate V3 on youtube, I was directed here from that video. I have messed around with some stuff and the mod works great except for it seems the chunk preload and force chunk preload feature don't do anything. (using ffmpeg3.4.2 and minema 3.4.4 in forge 1.12.2 recommended version with optifine)
are these features supposed to load all chunks in view of the player before rendering the next frame? That's what I believed they were for but there seems to be no difference between having them off and on. My videos come out with very large and obvious gaps where chunks slowly load in over several frames. Any fixes I can try on my end? (or do these features not actually do what I think they do)

**Comment by mchorse** [comment]
Hello, as far as I remember, force load chunks is speeding up the loading of chunks rather than constantly reloading all the chunks, and force preload feature preloads all the chunks but only when it's initially starts.

At the moment, I'm quite busy right now to investigate and make it work correctly. I.e. load all the unloaded chunks. You could give a try to accomplish this with ReplayMod. I'm not certain that it will work, but it's worth a try.
