### ISSUE TITLE
Minema crash on recording : Can't export frame

### ISSUE THREAD

**Issue by ghost** [daipenger/minema#2]
Hello, I'm on windows 8 and i use Minema 3.3 ShaderSyncEdition but when i try to start to record, i have a crash : [Pastcode Here](https://pastebin.com/NJi2dH1D)

FFmpeg 3.3.2 is installed and i tried several  Encoder Arguments but no one is working.
(Sorry for the bad English i'm French)

**Comment by daipenger** [comment]
Caused by: java.io.IOException: Le canal de communication a �t� ferm�

- Is your export folder (default: .minecraft\movies) already created? If not, create it by hand.
- Run Minecraft as administrator! 
- Missing permissions for writing to the export location/any write locks?
It should be one of those.

"i tried several Encoder Arguments": If you don't know exactly what you are doing, stop that. Use the default!
