### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by rojaoo** [daipenger/minema#29]
Is there a way to have audio with minema? Like a mod that does the same thing as minema, syncs the audio speed with the fps and when it saves it looks like real time.

**Comment by mchorse** [comment]
Besides recording audio separately using the most minimal graphics settings, I don't have any other solutions.

**Comment by HakkaTjakka** [comment]
You could export a list with timing and the sound played. Then afterward mix them all with ffmpeg.
If you put this in as an option i will build the ffmpeg site.

**Comment by rojaoo** [comment]
You should talk to McHorse on his Discord about it, it would be a amazing addiction to Minema.

**Comment by mchorse** [comment]
Guys, I quit Minecraft modding back in September “11. Just because I’m hanging still around, doesn’t mean I’m gonna implement any features.

**Comment by rojaoo** [comment]
Isn't Chryfi the current maintainer of minema? If yes, maybe he could implement something like this to minema, it would be a awesome update. It's a feature that have been missing for years.

**Comment by Chryfi** [comment]
I am not the maintainer of minema, I am working with the McHorse mods like Blockbuster, Aperture etc. at the moment. Also, at the moment I already have enough important features to implement, so I can't bother with this one. But I would gladly appreciate it if whoever wants to add this feature to minema joins the McHorse Discord server https://discord.gg/qfxrqUF so we can communicate and later have an official release with changelog video etc..

**Comment by rojaoo** [comment]
So, there's no maintainer for minema? I think it's time to learn Minecraft modding lol

**Comment by mchorse** [comment]
> So, there's no maintainer for minema? I think it's time to learn Minecraft modding lol

Maintainer doesn't mean someone who makes features for free, but yeah, the mod is so niche that there is currently no one who's willing to work on it anymore.

**Comment by HakkaTjakka** [comment]
If you have a nice manual on how the minema mod works in combination with Java, how to set up the ide etc., i would be gladly work on stuff. But i'm not going to take a full Java class or study to get dived into that shit. I'm not bragging but have 40 years of experience in c/c++ and assembler and all the stuff around it, and Java is also written in c/c++. But writing a real time graphics program like a game in Java is really stupid when it comes to performance. The only nice thing is that the code is reusable and can be adapted. Like the console and Windows 10 versions are closed systems you can not hack into. And its a shame not publishing the source code for it when the base of the game was.

I assume (like all software gets crippled and sabotaged because of commercial values) the code for 1.13+ is completely different and rewritten and then you get the stuff like optifine fabric forge shit etc.
That makes my point that the versioning is just a hell of chaos script kiddies working aside from each other.

Again i'm willing to spend some time on it if i have some introduction into the 1.12.2 version, the newer MC versions, and Forge and/or Fabric for modding (two incompatible systems), because normally it would not take much effort to adapt some timing functions inside MC and write a screen to an external ffmpeg. 
Window versions, Linux, Java versioning, MC versioning, mod versioning, different mod systems etc.
Why not everybody work together on one big platform with all the knowledge and documentation and information and start just one big project:

Rebuilding the whole thing in open source c/c++

Have you informed NASA on how to put a man on the moon with Java instead of a computer with the power of a pocket Japanese? 

Keep'm in the pants.

**Comment by HakkaTjakka** [comment]
Oh, what would be the budget to make it work on the newer (newest) MC version?
Then you could put up a donation site for people willing to put some recording stuff into some Java trash code.....
If so i would donate like $ 250,- for a newer minema mod system that wipes out the ReplayMod ego system.

**Comment by HakkaTjakka** [comment]
4 40 years ago computers were clean on the software and hardware site.
Now its a trashdump where you need to dig up stuff while the whole trashdump is moved around by commercial companies.
