### ISSUE TITLE
Only records the bottom half of screen when set to a 9:16 ratio

### ISSUE THREAD

**Issue by nerd0ne** [daipenger/minema#36]
When recording to a 9:16 ratio, it bugs out the top half of the recording and only records the bottom half of the screen. I was using the mod blockbuster while I was recording with minema.

**Comment by nerd0ne** [comment]
Here is the result

https://user-images.githubusercontent.com/103904665/170915698-7a6aba40-51fc-457c-b2cf-6f6a8ffe774f.mp4

**Comment by nerd0ne** [comment]
I also tried to record this without using the button in blockbuster and it recorded the same way

https://user-images.githubusercontent.com/103904665/171032791-2cdb9ede-1cf0-4683-a80d-b80dee307e0b.mp4

**Comment by mchorse** [comment]
I forgot to reply, but if anyone is still looking for solution, it's usually happens when you record in fullscreen, AND either Optifine's fast render or Shaders > Anti-aliasing is turned on. Disable both. If that won't help, try enabling Mod Options > Minema > Capturing > Fast render and anti-aliasing fix.
